package com.inspur.cams.comm.bsp.user;

public class Sql {

	/**
	/**
	 * 递归查询，授予用户的角色继承的角色和直接授予用户的角色。Oracle
	 */
	public final static String USER_INHERITED_ROLE_GROUP_ORACLE = (new StringBuffer()).append("WITH USER_ROLE AS (SELECT ROLE_ID FROM PUB_USER_ROLE WHERE TARGET=?) SELECT PUB_ROLES.ROLE_ID,PUB_ROLES.ROLE_NAME,PUB_ROLES.RELATION_ID,PUB_ROLES.ROLE_GROUP_ID,PUB_ROLES.DESCRIPTION FROM ")
	.append("(SELECT GRANTED_ROLE FROM PUB_ROLE_PRIVS START WITH ROLE_ID IN (SELECT ROLE_ID FROM USER_ROLE) CONNECT BY PRIOR GRANTED_ROLE=ROLE_ID UNION ALL SELECT ROLE_ID FROM USER_ROLE) ")
	.append("ROLE_PRIVS,PUB_ROLES WHERE ROLE_PRIVS.GRANTED_ROLE=PUB_ROLES.ROLE_ID AND ROLE_GROUP_ID=?").toString();

}
