// 单值图的基本信息(最小值,最大值,显示几种颜色)
var svColor = "1|174";

// 单值图的全部信息
var svData = "<nodes><node field=\"济南市\" value=\"1\" /> <node field=\"青岛市\" value=\"30\" />"
		+ "<node field=\"淄博市\" value=\"52.499\" /> <node field=\"德州市\" value=\"101\" />"
		+ "<node field=\"烟台市\" value=\"52.51\" /> <node field=\"潍坊市\" value=\"104\" />"
		+ "<node field=\"济宁市\" value=\"1\" /> <node field=\"泰安市\" value=\"35.331\" />"
		+ "<node field=\"临沂市\" value=\"52.509\" /> <node field=\"菏泽市\" value=\"35.329\" />"
		+ "<node field=\"莱芜市\" value=\"1\" /> <node field=\"东营市\" value=\"11\" />"
		+ "<node field=\"滨州市\" value=\"37\" /></nodes>";

// 饼图的全部信息
var pieData = value = "<pieSource>"
		+ "<root key=\"习水\">"
		+ "<node field=\"结婚\" value=\"21220\" /> <node field=\"离婚\" value=\"3820\" />"
		+ "</root>"
		+ "<root key=\"济南市\">"
		+ "<node field=\"结婚\" value=\"65338\" /> <node field=\"离婚\" value=\"12368\" />"
		+ "</root>"
		+ "<root key=\"青岛市\">"
		+ "<node field=\"结婚\" value=\"78903\" /> <node field=\"离婚\" value=\"14466\" />"
		+ "</root>"
		+ "<root key=\"淄博市\">"
		+ "<node field=\"结婚\" value=\"34567\" /> <node field=\"离婚\" value=\"7407\" />"
		+ "</root>"
		+ "<root key=\"枣庄市\">"
		+ "<node field=\"结婚\" value=\"39181\" /> <node field=\"离婚\" value=\"6061\" />"
		+ "</root>"
		+ "<root key=\"烟台市\">"
		+ "<node field=\"结婚\" value=\"61007\" /> <node field=\"离婚\" value=\"11711\" />"
		+ "</root>"
		+ "<root key=\"潍坊市\">"
		+ "<node field=\"结婚\" value=\"85326\" /> <node field=\"离婚\" value=\"10153\" />"
		+ "</root>"
		+ "<root key=\"济宁市\">"
		+ "<node field=\"结婚\" value=\"95633\" /> <node field=\"离婚\" value=\"10467\" />"
		+ "</root>"
		+ "<root key=\"泰安市\">"
		+ "<node field=\"结婚\" value=\"57973\" /> <node field=\"离婚\" value=\"6105\" />"
		+ "</root>"
		+ "<root key=\"威海市\">"
		+ "<node field=\"结婚\" value=\"21918\" /> <node field=\"离婚\" value=\"3850\" />"
		+ "</root>"
		+ "<root key=\"德州市\">"
		+ "<node field=\"结婚\" value=\"60584\" /> <node field=\"离婚\" value=\"7151\" />"
		+ "</root>"
		+ "<root key=\"临沂市\">"
		+ "<node field=\"结婚\" value=\"117634\" /> <node field=\"离婚\" value=\"12044\" />"
		+ "</root>"
		+ "<root key=\"菏泽市\">"
		+ "<node field=\"结婚\" value=\"95164\" /> <node field=\"离婚\" value=\"9161\" />"
		+ "</root>"
		+ "<root key=\"莱芜市\">"
		+ "<node field=\"结婚\" value=\"9174\" /> <node field=\"离婚\" value=\"1229\" />"
		+ "</root>"
		+ "<root key=\"东营市\">"
		+ "<node field=\"结婚\" value=\"17434\" /> <node field=\"离婚\" value=\"3018\" />"
		+ "</root>"
		+ "<root key=\"滨州市\">"
		+ "<node field=\"结婚\" value=\"38716\" /> <node field=\"离婚\" value=\"4799\" />"
		+ "</root>"
		+ "<root key=\"湄潭\">"
		+ "<node field=\"结婚\" value=\"30\" /> <node field=\"离婚\" value=\"30\" />"
		+ "</root>" + "</pieSource>";